/**
 * Minimal HTML extraction.
 *
 * Regex parsing is acceptable here — and ONLY here — because every file these
 * helpers touch is generated by templates in this repository. Do not point them
 * at arbitrary HTML. See PLAN.md §5.
 */

const NAMED_ENTITIES = {
    amp: '&',
    lt: '<',
    gt: '>',
    quot: '"',
    apos: "'",
    nbsp: ' ',
    mdash: '—',
    ndash: '–',
    hellip: '…',
    lsquo: '‘',
    rsquo: '’',
    ldquo: '“',
    rdquo: '”',
};

function stripComments(html) {
    return html.replace(/<!--[\s\S]*?-->/g, '');
}

function decodeEntities(str) {
    return str.replace(/&(#[xX]?[0-9a-fA-F]+|[a-zA-Z][a-zA-Z0-9]*);/g, (match, code) => {
        if (code[0] === '#') {
            const isHex = code[1] === 'x' || code[1] === 'X';
            const n = parseInt(isHex ? code.slice(2) : code.slice(1), isHex ? 16 : 10);
            return Number.isFinite(n) ? String.fromCodePoint(n) : match;
        }
        return Object.prototype.hasOwnProperty.call(NAMED_ENTITIES, code)
            ? NAMED_ENTITIES[code]
            : match;
    });
}

/** Visible text, whitespace-normalised. Scripts and styles are dropped. */
function text(html) {
    const withoutCode = stripComments(html)
        .replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ')
        .replace(/<[^>]+>/g, ' ');
    return decodeEntities(withoutCode).replace(/\s+/g, ' ').trim();
}

/**
 * Inner HTML of the first `<tag class="... className ...">`, tracking nested
 * same-name tags so the matching close tag is found rather than the first one.
 * Returns null when absent.
 */
function extractElement(html, tag, className) {
    const opener = new RegExp(
        `<${tag}\\b[^>]*\\bclass\\s*=\\s*"[^"]*\\b${className}\\b[^"]*"[^>]*>`,
        'i'
    );
    const found = opener.exec(html);
    if (!found) return null;

    const start = found.index + found[0].length;
    const tokens = new RegExp(`<${tag}\\b[^>]*?(/?)>|</${tag}\\s*>`, 'gi');
    tokens.lastIndex = start;

    let depth = 1;
    let token;
    while ((token = tokens.exec(html)) !== null) {
        const isClosing = token[0].startsWith('</');
        const isSelfClosing = token[1] === '/';
        if (isClosing) {
            depth -= 1;
            if (depth === 0) return html.slice(start, token.index);
        } else if (!isSelfClosing) {
            depth += 1;
        }
    }
    return null;
}

function countTags(html, tag) {
    return (html.match(new RegExp(`<${tag}\\b`, 'gi')) || []).length;
}

/** All values of a double-quoted attribute, in document order. */
function attrValues(html, attr) {
    const re = new RegExp(`\\b${attr}\\s*=\\s*"([^"]*)"`, 'gi');
    const values = [];
    let match;
    while ((match = re.exec(html)) !== null) values.push(match[1]);
    return values;
}

/** Every class name used anywhere in the document. */
function classNames(html) {
    const names = new Set();
    for (const value of attrValues(html, 'class')) {
        value.split(/\s+/).filter(Boolean).forEach((name) => names.add(name));
    }
    return names;
}

/** Unreplaced template placeholders, e.g. a forgotten {{title}}. */
function placeholders(html) {
    return html.match(/\{\{[^}]*\}\}/g) || [];
}

function wordCount(str) {
    return str ? str.split(/\s+/).filter(Boolean).length : 0;
}

module.exports = {
    stripComments,
    decodeEntities,
    text,
    extractElement,
    countTags,
    attrValues,
    classNames,
    placeholders,
    wordCount,
};
